# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import utils.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elapsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=63)),
                ('elapsed', models.IntegerField()),
            ],
            bases=(utils.misc.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=63)),
                ('start', models.BigIntegerField()),
            ],
            bases=(utils.misc.ModelMixin, models.Model),
        ),
    ]
