# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0002_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedCookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
            ],
            bases=(utils.misc.ModelMixin, models.Model),
        ),
    ]
