# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0004_add_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abbrev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='autoupdate',
            field=models.BooleanField(default=True),
        ),
    ]
