# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-07 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0005_make_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='showIntro',
            field=models.BooleanField(default=True),
        ),
    ]
